fieldLayouts:
  77b4b518-6118-4810-9924-146f4be0a821:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3f9a5161-7384-4d9e-9db8-782b2bd02bf4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7e1e2c1c-1ce9-42ca-92ca-1292b0878ca4
        userCondition: null
fs: caseStudiesImage
handle: caseStudiesImage
name: 'Carousel Image'
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
