fieldLayouts:
  a21d1b8f-0f45-4eb9-aaa3-998383797f9a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 930ed66e-4a60-449d-9589-9cc82558dae3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68acde87-0dc8-416f-b698-e5db4669c03a
        userCondition: null
fs: clientLogo
handle: clientsLogo
name: 'Clients Logo'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
