fieldLayouts:
  5fdb13f0-e4ea-4fd1-9c37-28560e00db91:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3fc138bc-0e8c-45ad-a889-270e41d22d63
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dd5f0adb-96b1-43e4-99de-17eb36191277
        userCondition: null
fs: menuImage
handle: menuImage
name: 'Menu Image'
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
