fieldLayouts:
  77efedc2-54b5-4e3a-8e92-6f3e2e61ff49:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b390161c-e82c-45bc-bea8-53859ac508bc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d2c096bc-c48d-46f7-9c35-15fdadcfa71e
        userCondition: null
fs: profileImage
handle: profileImage
name: 'Profile Image'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: profileImage
transformSubpath: ''
