changedFieldIndicator: 958154711
field: cc78163c-dff2-4b88-9ed0-7b35e1d8939f # Projects
fieldLayouts:
  938e3af8-4f89-4a7f-a405-af6f68e542be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a4e13130-2b23-40dd-bd1a-0624c22b1cb3 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6eef3440-b82d-4c53-8792-887545f69940
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc45a24c-9f11-481e-b893-7cad649aa403 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3fd5873-1222-4939-8abd-e07e9733e1d4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f6c8c9b3-a1b9-4085-bc58-84e304578340 # Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c165c879-bab7-4383-ac5d-f438d98a211c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11270822-831b-4696-a709-33299f2d602c
        userCondition: null
fields:
  a4e13130-2b23-40dd-bd1a-0624c22b1cb3: # Video
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: video
    instructions: 'If video is upload then video will populate.'
    name: Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - video
      defaultUploadLocationSource: 'volume:cd2572e3-fdd2-482c-8457-7c30f7926815' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:cd2572e3-fdd2-482c-8457-7c30f7926815' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add Video'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:cd2572e3-fdd2-482c-8457-7c30f7926815' # Uploads
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f6c8c9b3-a1b9-4085-bc58-84e304578340: # Type
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: workType
    instructions: null
    name: Type
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: 'Add Work Type'
      showSiteMenu: true
      source: null
      sources:
        - 'section:5cf99201-1ee3-43c4-b76d-fd3ed615a764' # Work Categories
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  fc45a24c-9f11-481e-b893-7cad649aa403: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:cd2572e3-fdd2-482c-8457-7c30f7926815' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:cd2572e3-fdd2-482c-8457-7c30f7926815' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:cd2572e3-fdd2-482c-8457-7c30f7926815' # Uploads
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
