fieldLayouts:
  11e8abfc-a903-45af-a243-f79d1aee9967:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e285fadb-2171-41a6-a8c0-b6affbc4f9b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: feea77ae-01ed-45ef-b994-a8a3a437f73e # About
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19bd10a2-3e6c-4304-ae13-4b599c6f3e99
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c4d6a40-bd46-446b-a85d-38bbd8998689 # Client Logos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c44b2bd-fa17-4119-b0f0-7a1b378032f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bf6c8d6-1d56-4236-9c1e-6e8d1dd45746 # Right Image
            instructions: 'This will display in the menu when user hove the Menu title'
            label: 'Menu Right Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc03d92a-c681-42e8-8fb5-9c8d28592c06
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 863a85cd-1566-488d-a7b0-6e14798a99a8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bde0d11b-0956-4e82-a8d7-a6ea1643030b # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53a29f07-f81e-4e6a-88c8-41b4a5261d59
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: 8be24249-203c-4d2f-ae70-30e8189c7593
        userCondition: null
handle: clients
hasTitleField: true
name: Clients
section: bf0ed4e5-904b-41ce-9bea-fe7177e87aad # Clients
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
