fieldLayouts:
  42326f7e-1e83-42db-955e-25611c59772d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3fb282cf-5750-4981-8786-798396fd8833
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: feea77ae-01ed-45ef-b994-a8a3a437f73e # About
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3a26408-f48c-4016-b27d-75ef106900e4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bf6c8d6-1d56-4236-9c1e-6e8d1dd45746 # Right Image
            instructions: 'This will display in the right side, when menu title hover'
            label: 'Menu Right Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c4a7cac-7edd-4be7-b145-71974ccb8b2e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6cfc2aa8-a9db-4fa7-a040-008b79145b05 # Work Listing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ebb94bf-236b-43e6-a570-b217263599a4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 26697450-08a9-4f0a-bab1-c13be5a432e3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bde0d11b-0956-4e82-a8d7-a6ea1643030b # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9980eaa-c18d-4a86-bbe8-a90d44949b9f
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: f8492ae9-5335-469c-99b3-9d2daf83769b
        userCondition: null
handle: work
hasTitleField: true
name: Work
section: b54c340c-eaa8-443a-9bf3-effd8769efdc # Work
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
