fieldLayouts:
  2005c3af-b2ad-426d-ae94-6ebe5c0efcb3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 21ecc6e1-16f7-49aa-aaa5-e21e65c3fe99 # Left Menu Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7ea2b5e-4e18-4dd3-ac81-eef6ff713810
            userCondition: null
            warning: null
            width: 100
        name: 'Left Menu'
        uid: 0ddbb72e-1dd7-4959-adee-759684e38232
        userCondition: null
handle: leftMenu
name: 'Left Menu'
sortOrder: 2
