fieldLayouts:
  ab9c5c77-96a6-4c2c-9418-7613616f8d99:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 60a62108-a7d5-4a7d-959f-87264388a217 # Right Menu Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fa7acf6-78be-49fe-b476-c8c560b9c465
            userCondition: null
            warning: null
            width: 100
        name: 'Right Menu'
        uid: 6bd32c13-65f0-4508-b03f-56fe00c6f4df
        userCondition: null
handle: rightMenu
name: 'RIght Menu'
sortOrder: 3
