defaultPlacement: end
enableVersioning: true
handle: caseStudies
name: 'Case Studies'
propagationMethod: all
siteSettings:
  041418b2-de26-4fce-b148-9268234e99d2: # branding-phi
    enabledByDefault: true
    hasUrls: true
    template: case-studies/_entry
    uriFormat: 'work/{slug}'
type: channel
