defaultPlacement: end
enableVersioning: true
handle: clients
name: Clients
propagationMethod: all
siteSettings:
  041418b2-de26-4fce-b148-9268234e99d2: # branding-phi
    enabledByDefault: true
    hasUrls: true
    template: clients/_entry
    uriFormat: '{slug}'
type: single
