defaultPlacement: end
enableVersioning: true
handle: landingPages
name: 'Landing Pages'
propagationMethod: all
siteSettings:
  041418b2-de26-4fce-b148-9268234e99d2: # branding-phi
    enabledByDefault: true
    hasUrls: true
    template: landing-pages/_entry
    uriFormat: '{slug}'
type: channel
