fieldLayouts:
  66295196-ff91-4030-b465-fd8c888d4d14:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 652b2d5a-94dc-4054-b2a2-4e6c92f450a4 # Right Menu Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c00c8e76-5353-41c5-8067-0b2d5678d350
            userCondition: null
            warning: null
            width: 100
        name: 'RIght Menu'
        uid: af88243a-44f4-4b2d-b481-9ab19e738068
        userCondition: null
handle: rightMenu
name: 'RIght Menu'
sortOrder: 3
