columnSuffix: null
contentColumnType: string
fieldGroup: 6a6d7227-151f-40cd-a464-0926591db9b5 # Common
handle: artistTitle
instructions: null
name: 'Artist Title'
searchable: false
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: 'Add Title'
  showSiteMenu: false
  source: null
  sources:
    - 'section:31270e17-7e6b-4284-a863-d7d474e6a142' # Artist Title
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
