columnSuffix: firimnsy
contentColumnType: string(255)
fieldGroup: 6a6d7227-151f-40cd-a464-0926591db9b5 # Common
handle: instagramUrl
instructions: null
name: 'Instagram URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
