fieldLayouts:
  375b84a5-47a7-42c5-8ce9-ed13391c2495:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d471d6d7-66c0-42db-931c-d15501792f2c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: feea77ae-01ed-45ef-b994-a8a3a437f73e # About
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2d95fb3-2c95-4765-ae1f-bdc6e9ad2daf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a5da4fcb-febc-449f-b7dc-81427182756f # Client Logos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 788c8d02-4a90-4fd5-8dca-e77f4e82fd73
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bf6c8d6-1d56-4236-9c1e-6e8d1dd45746 # Right Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d409763f-9dbf-4166-aaed-4d3919e05e0d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7a7ccbb7-ea27-463c-a0ae-4544db164791
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bde0d11b-0956-4e82-a8d7-a6ea1643030b # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 294ce9ea-5faf-4c33-86d0-a99f44604a74
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: c2efc870-52ec-4a32-9c2d-5db02f152e29
        userCondition: null
handle: clients
hasTitleField: true
name: Clients
section: c8843fc4-26f6-497b-a618-09f595732e46 # Clients
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
