defaultPlacement: end
enableVersioning: true
handle: artists
name: Artists
propagationMethod: all
siteSettings:
  041418b2-de26-4fce-b148-9268234e99d2: # branding-phi
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: d1df58dc-79d5-4977-ba25-ac505589be41
type: structure
