defaultPlacement: end
enableVersioning: true
handle: artistTitle
name: 'Artist Title'
propagationMethod: all
siteSettings:
  041418b2-de26-4fce-b148-9268234e99d2: # branding-phi
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 96b11e61-04b4-4b85-aecc-271a87422ce5
type: structure
