columnSuffix: fvqdmfmh
contentColumnType: string
fieldGroup: 6a6d7227-151f-40cd-a464-0926591db9b5 # Common
handle: careerEmail
instructions: null
name: 'Career Email'
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
