columnSuffix: null
contentColumnType: string
fieldGroup: 6a6d7227-151f-40cd-a464-0926591db9b5 # Common
handle: caseStudies
instructions: null
name: 'Case Studies'
searchable: false
settings:
  contentTable: '{{%matrixcontent_casestudies}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
